from enum import Enum


class TransportEvent(Enum):
    OPENED = "OPENED"
    CLOSED = "CLOSED"
    TIMEOUT = "TIMEOUT"
    DROPPED = "DROPPED"
    ACK_RECEIVED = "ACK_RECEIVED"
    REPLY_RECEIVED = "REPLY_RECEIVED"
    REPLY_FORWARDED = "REPLY_FORWARDED"
    REPLY_ERROR = "REPLY_ERROR"
    UNEXPECTED_REPLY = "UNEXPECTED_REPLY"
    MALFORMED_REPLY = "MALFORMED_REPLY"
    READ_ERROR = "READ_ERROR"
