#!/usr/bin/env bash
_self=$(basename "$0")
usage () {
  cat <<EOF
Usage: $_self <ip> <file> [<options>]

Use this script to run tshark to capture a log file which can then be processed
using decode.

Parameters:
 1 The Ruida controller IP address.
 2 The capture file name -- not including extension. This saves to <file>.log.
 3 Optional parameters. (e.g. "-i <if>", "--tcp")

Options:
 --tcp    Capture the Ruida TCP stream on port 50200 instead of UDP.
 --udp    Capture Ruida UDP traffic (the default).

NOTE: Parameter 3 is often needed on Windows because it typically assumes the
wrong interface. If this is the case use "-i Ethernet".
EOF
exit 1
}

if [ "$#" -lt 2 ]; then
    usage
fi

_ip=$1

_os=`uname | cut -d ' ' -f 1`
if [ "$_os" = "Linux" ]; then
    ping -c 1 -W 1 "$_ip"
else
    # Assuming Windows for now.
    ping -n 1 -w 100 "$_ip"
fi
if [ $? -ne 0 ]; then
    # Be forgiving since a bogus ip or having machine off may be intentional
    # when capturing lost comms behaviors.
    echo Warning: IP address $_ip is not reachable.
    echo Is the machine OFF?
else
    echo IP address is reachable.
fi

_file=$2

_path=$(dirname $_file)
if [ -e $_path ]; then
    _proto=udp
    _tshark_args=()
    for _arg in "${@:3}"; do
        case "$_arg" in
            --tcp) _proto=tcp ;;
            --udp) _proto=udp ;;
            *) _tshark_args+=("$_arg") ;;
        esac
    done
    if [ "$_proto" = "tcp" ]; then
        _filter="(ip.addr == $_ip && tcp.port == 50200)"
        _fields="-e frame.time_delta -e tcp.srcport -e tcp.dstport -e tcp.len -e tcp.payload"
    else
        _filter="(ip.addr == $_ip)"
        _fields="-e frame.time_delta -e udp.port -e udp.length -e data.data"
    fi
    tshark -Y "$_filter" "${_tshark_args[@]}" -l -T fields \
        $_fields | tee $_file.log
else
    echo Log file path $_path does not exist.
    usage
fi
